apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openstack

configMapGenerator:
  - name: sunrise-novnc
    files:
      - sunrise.html
      - sunrise.css
      - sunrise.js
