export const statusColorMap: { [index: string]: string } = {
    ACTIVE: "success",
    AVAILABLE:"success",
    ERROR: "danger",
    BUILD: "warning",
    DELETED: "default",
    DELETING: "default",
    HARD_REBOOT: "default",
    IN_USE: "default",
    MIGRATING: "default",
    PASSWORD: "default",
    PAUSED: "default",
    REBOOT: "default",
    REBUILD: "default",
    RESCUE: "default",
    RESIZE: "default",
    REVERT_RESIZE: "default",
    SHELVED: "default",
    SHELVED_OFFLOADED: "default",
    SHUTOFF: "default",
    SOFT_DELETED: "default",
    SUSPENDED: "default",
    UNKNOWN: "default",
    VERIFY_RESIZE: "default",
  };