import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { session } from "@/lib/session";
import { Providers } from "./providers";
import { Sidebar } from "@/components/sidebar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: {
    template: "%s - Sunrise",
    default: "Sunrise",
  },
  description: "Generated by Sunrise",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const projects = await session().get("projects");
  const selectedProject = await session().get("selectedProject");
  const userName = await session().get("userName");

  return (
    <html lang="en" className="h-full light">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased h-full",
          fontSans.variable,
        )}
      >
        <Providers>
          <Sidebar selectedProject={selectedProject} projects={projects} userName={userName} />
          <div className="lg:pl-72">
            <main className="py-10">
              <div className="px-4 sm:px-6 lg:px-8">{children}</div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
