import "./globals.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { getSession } from "@/lib/session";
import { Providers } from "./providers";
import { NavigationMenu } from "@/components/NavigationMenu";
import { ThemeProvider } from "@/components/ThemeProvider";
import { RegionProvider } from "@/contexts/RegionContext";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: {
    template: "%s - Sunrise",
    default: "Sunrise",
  },
  description: "Generated by Sunrise",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  return (
    <html lang="en" className="h-full light" suppressHydrationWarning>

      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased h-full",
          fontSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <RegionProvider initialRegion={session.selectedRegion}>
            <Providers>
              <NavigationMenu
                initialProjectId={session.selectedProject?.id}
                currentRegion={session.selectedRegion}
                userName={session.userName}
              />
              <main>
                {children}
              </main>
            </Providers>
          </RegionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
