const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "Instance Name", uid: "instance_name", sortable: true},
  {name: "Image Name", uid: "image_name", sortable: true},
  {name: "IP Address", uid: "ip_address", sortable: true},
  {name: "Flavor", uid: "flavor"},
  {name: "Key Pair", uid: "key_pair"},
  {name: "Status", uid: "status", sortable: true},
  {name: "Alert", uid: "alert"},
  {name: "Availability Zone", uid: "availability_zone"},
  {name: "Task", uid: "task"},
  {name: "Power Stage", uid: "power_stage"},
  {name: "Age", uid: "age"},
  {name: "Actions", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Paused", uid: "paused"},
  {name: "Vacation", uid: "vacation"},
];

const data = [
    { 
        id: 1,
        instance_name: 'test1', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 2,
        instance_name: 'test2', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 3,
        instance_name: 'test3', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 4,
        instance_name: 'test4', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 5,
        instance_name: 'test5', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 6,
        instance_name: 'test6', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 7,
        instance_name: 'test7', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 8,
        instance_name: 'test8', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 9,
        instance_name: 'test9', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 10,
        instance_name: 'test10', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 11,
        instance_name: 'test11', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    { 
        id: 12,
        instance_name: 'test12', 
        image_name: 'magnum-ubuntu-2204-kube-v1.27.3', 
        ip_address: '10.11.12.13', 
        flavor: 'm1.small',
        key_pair: 'my-key',
        status: 'Active',
        alert: false,
        availability_zone: 'nova',
        task: 'None',
        power_stage: 'Running',
        age: '1 week, 1 day',
        actions: '',
    },
    // More instances...
  ]

  export { columns, data, statusOptions }
